sudo: false
language: node_js
node_js:
  - 8
  - 9
  - 10

env:
  global:
    - BUILD_TIMEOUT=10000
install:
  - npm install
  - npm install cypress
  - npm install -g codecov
script:
  - npm run cov > coverage.lcov && codecov

