dist: trusty
sudo: false
language: node_js
node_js:
  - "lts/*"

env:
  global:
    - BUILD_TIMEOUT=10000
    - BASE_URL=sapper-cellular-automata
    - CYPRESS_BASE_URL=http://localhost:3030/$BASE_URL
before_install:
  - npm i -g npm@6
install:
  - npm ci
jobs:
  include:
    - stage: test
      script:
        - npm i cypress
        - npm run dev &
        - npm run cy:record
        - kill %1
    - # unit tests
      script:
        - npm run cov > coverage.lcov && codecov
    - stage: build
      after_success:
        - npm run export -- --basepath $BASE_URL
    - stage: deploy
      before_deploy:
        - mv -v export/${BASE_URL}/* .; ls .
        - touch .nojekyll # stop ignoring files staring with _, ., # or ~
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
