sudo: false
language: node_js
node_js:
  - "stable"
  - "lts/*"

env:
  global:
    - BUILD_TIMEOUT=10000
before_install:
  - npm i -g npm@6
install:
  - npm ci
script:
  - npm run dev &
  - npm run cy:run
  - npm run cov > coverage.lcov && codecov

