sudo: false
language: node_js
node_js:
  - "current"
env:
  global:
    - BUILD_TIMEOUT=10000
install:
  - npm i -g pnpm
  - pnpm i
  - pnpm i -g codecov
script:
  - pnpm run cov > coverage.lcov && codecov

