sudo: false
language: node_js
node_js:
  - "stable"
env:
  global:
    - BUILD_TIMEOUT=10000
install:
  - npm install
  - npm install cypress
  - npm install -g codecov
script:
  - npm run cov > coverage.lcov && codecov

