dist: trusty
sudo: false
language: node_js
node_js:
  - "stable"
  - "lts/*"

env:
  global:
    - BUILD_TIMEOUT=10000
    - BASE_URL=sapper-cellular-automata
    - CYPRESS_BASE_URL=http://localhost:3030/$BASE_URL
before_install:
  - npm i -g npm@6
install:
  - npm ci
script:
  - npm run dev &
  - npm run cy:record
  - kill %1
  - npm run cov > coverage.lcov && codecov
after_success:
  - BASE_URL=$BASE_URL npm run export --basepath $BASE_URL
before_deploy:
  - mv -v export/* .; ls .
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
